//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace PIMEdoc_CR.PIMWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="GetPositionBinding", Namespace="https://intranet.pim.ac.th/soap/GetPosition")]
    public partial class GetPosition : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback AuthenLDAPOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStudentProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStaffProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDepartmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllStaffProfileOperationCompleted;
        
        private System.Threading.SendOrPostCallback CallGetPositionOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public GetPosition() {
            this.Url = "https://intranet.pim.ac.th/wspim/wscore_pim.php";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event AuthenLDAPCompletedEventHandler AuthenLDAPCompleted;
        
        /// <remarks/>
        public event GetStudentProfileCompletedEventHandler GetStudentProfileCompleted;
        
        /// <remarks/>
        public event GetStaffProfileCompletedEventHandler GetStaffProfileCompleted;
        
        /// <remarks/>
        public event GetDepartmentCompletedEventHandler GetDepartmentCompleted;
        
        /// <remarks/>
        public event GetAllStaffProfileCompletedEventHandler GetAllStaffProfileCompleted;
        
        /// <remarks/>
        public event CallGetPositionCompletedEventHandler CallGetPositionCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://intranet.pim.ac.th/wspim/wscore_pim.php/AuthenLDAP", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string AuthenLDAP(string strName, string strPass) {
            object[] results = this.Invoke("AuthenLDAP", new object[] {
                        strName,
                        strPass});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AuthenLDAPAsync(string strName, string strPass) {
            this.AuthenLDAPAsync(strName, strPass, null);
        }
        
        /// <remarks/>
        public void AuthenLDAPAsync(string strName, string strPass, object userState) {
            if ((this.AuthenLDAPOperationCompleted == null)) {
                this.AuthenLDAPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAuthenLDAPOperationCompleted);
            }
            this.InvokeAsync("AuthenLDAP", new object[] {
                        strName,
                        strPass}, this.AuthenLDAPOperationCompleted, userState);
        }
        
        private void OnAuthenLDAPOperationCompleted(object arg) {
            if ((this.AuthenLDAPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AuthenLDAPCompleted(this, new AuthenLDAPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://intranet.pim.ac.th/wspim/wscore_pim.php/GetStudentProfile", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string GetStudentProfile(string strName, string strPass, string strStudentcode) {
            object[] results = this.Invoke("GetStudentProfile", new object[] {
                        strName,
                        strPass,
                        strStudentcode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetStudentProfileAsync(string strName, string strPass, string strStudentcode) {
            this.GetStudentProfileAsync(strName, strPass, strStudentcode, null);
        }
        
        /// <remarks/>
        public void GetStudentProfileAsync(string strName, string strPass, string strStudentcode, object userState) {
            if ((this.GetStudentProfileOperationCompleted == null)) {
                this.GetStudentProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStudentProfileOperationCompleted);
            }
            this.InvokeAsync("GetStudentProfile", new object[] {
                        strName,
                        strPass,
                        strStudentcode}, this.GetStudentProfileOperationCompleted, userState);
        }
        
        private void OnGetStudentProfileOperationCompleted(object arg) {
            if ((this.GetStudentProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStudentProfileCompleted(this, new GetStudentProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://intranet.pim.ac.th/wspim/wscore_pim.php/GetStaffProfile", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string GetStaffProfile(string strName, string strPass, string strStaffcode) {
            object[] results = this.Invoke("GetStaffProfile", new object[] {
                        strName,
                        strPass,
                        strStaffcode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetStaffProfileAsync(string strName, string strPass, string strStaffcode) {
            this.GetStaffProfileAsync(strName, strPass, strStaffcode, null);
        }
        
        /// <remarks/>
        public void GetStaffProfileAsync(string strName, string strPass, string strStaffcode, object userState) {
            if ((this.GetStaffProfileOperationCompleted == null)) {
                this.GetStaffProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStaffProfileOperationCompleted);
            }
            this.InvokeAsync("GetStaffProfile", new object[] {
                        strName,
                        strPass,
                        strStaffcode}, this.GetStaffProfileOperationCompleted, userState);
        }
        
        private void OnGetStaffProfileOperationCompleted(object arg) {
            if ((this.GetStaffProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStaffProfileCompleted(this, new GetStaffProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://intranet.pim.ac.th/wspim/wscore_pim.php/GetDepartment", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string GetDepartment(string strName, string strPass, string strDepartmentID) {
            object[] results = this.Invoke("GetDepartment", new object[] {
                        strName,
                        strPass,
                        strDepartmentID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDepartmentAsync(string strName, string strPass, string strDepartmentID) {
            this.GetDepartmentAsync(strName, strPass, strDepartmentID, null);
        }
        
        /// <remarks/>
        public void GetDepartmentAsync(string strName, string strPass, string strDepartmentID, object userState) {
            if ((this.GetDepartmentOperationCompleted == null)) {
                this.GetDepartmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDepartmentOperationCompleted);
            }
            this.InvokeAsync("GetDepartment", new object[] {
                        strName,
                        strPass,
                        strDepartmentID}, this.GetDepartmentOperationCompleted, userState);
        }
        
        private void OnGetDepartmentOperationCompleted(object arg) {
            if ((this.GetDepartmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDepartmentCompleted(this, new GetDepartmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://intranet.pim.ac.th/wspim/wscore_pim.php/GetAllStaffProfile", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string GetAllStaffProfile(string strName, string strPass, string strPrimaryPosition) {
            object[] results = this.Invoke("GetAllStaffProfile", new object[] {
                        strName,
                        strPass,
                        strPrimaryPosition});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllStaffProfileAsync(string strName, string strPass, string strPrimaryPosition) {
            this.GetAllStaffProfileAsync(strName, strPass, strPrimaryPosition, null);
        }
        
        /// <remarks/>
        public void GetAllStaffProfileAsync(string strName, string strPass, string strPrimaryPosition, object userState) {
            if ((this.GetAllStaffProfileOperationCompleted == null)) {
                this.GetAllStaffProfileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllStaffProfileOperationCompleted);
            }
            this.InvokeAsync("GetAllStaffProfile", new object[] {
                        strName,
                        strPass,
                        strPrimaryPosition}, this.GetAllStaffProfileOperationCompleted, userState);
        }
        
        private void OnGetAllStaffProfileOperationCompleted(object arg) {
            if ((this.GetAllStaffProfileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllStaffProfileCompleted(this, new GetAllStaffProfileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://intranet.pim.ac.th/wspim/wscore_pim.php/GetPosition", RequestNamespace="", ResponseNamespace="")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public string CallGetPosition(string strName, string strPass, string strPositionID) {
            object[] results = this.Invoke("CallGetPosition", new object[] {
                        strName,
                        strPass,
                        strPositionID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CallGetPositionAsync(string strName, string strPass, string strPositionID) {
            this.CallGetPositionAsync(strName, strPass, strPositionID, null);
        }
        
        /// <remarks/>
        public void CallGetPositionAsync(string strName, string strPass, string strPositionID, object userState) {
            if ((this.CallGetPositionOperationCompleted == null)) {
                this.CallGetPositionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCallGetPositionOperationCompleted);
            }
            this.InvokeAsync("CallGetPosition", new object[] {
                        strName,
                        strPass,
                        strPositionID}, this.CallGetPositionOperationCompleted, userState);
        }
        
        private void OnCallGetPositionOperationCompleted(object arg) {
            if ((this.CallGetPositionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CallGetPositionCompleted(this, new CallGetPositionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void AuthenLDAPCompletedEventHandler(object sender, AuthenLDAPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AuthenLDAPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AuthenLDAPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetStudentProfileCompletedEventHandler(object sender, GetStudentProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStudentProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStudentProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetStaffProfileCompletedEventHandler(object sender, GetStaffProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStaffProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStaffProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetDepartmentCompletedEventHandler(object sender, GetDepartmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDepartmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDepartmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void GetAllStaffProfileCompletedEventHandler(object sender, GetAllStaffProfileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllStaffProfileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllStaffProfileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    public delegate void CallGetPositionCompletedEventHandler(object sender, CallGetPositionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2558.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CallGetPositionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CallGetPositionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591